name: Run Browser Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: Which test suites to run
        type: choice
        default: browser
        options:
          - browser
          - accessibility
  workflow_call:
    inputs:
      suite:
        description: Which test suites to run
        type: string
        default: browser

defaults:
  run:
    shell: bash

# Required for OIDC with AWS
permissions:
  id-token: write
  contents: read

concurrency:
  group: browser-tests-${{ inputs.suite }}
  cancel-in-progress: false

jobs:
  browser-tests:
    name: Browser tests
    runs-on: ubuntu-latest
    environment: aws-dev

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Zip source repository
        run: zip -r -q hfu-browser-tests.zip . -x '.git/*'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_CODEBUILD_ROLE_TO_ASSUME }}
          role-session-name: BrowserTests-${{ github.run_id }}

      - name: Upload zip to S3
        run: aws s3 cp hfu-browser-tests.zip s3://hfurb-data-deployments-source-code-bucket-dev/hfu-browser-tests.zip

      - name: Run browser tests in CodeBuild
        uses: aws-actions/aws-codebuild-run-build@7e46c3fa1c1f217e26a73712796b1f78938b534b # v1.0.19
        env:
          BROWSER_TEST_SUITE: ${{ inputs.suite }}
        with:
          project-name: hfu-browser-tests-codebuild-dev
          source-type-override: S3
          source-location-override: hfurb-data-deployments-source-code-bucket-dev/hfu-browser-tests.zip
          env-vars-for-codebuild: BROWSER_TEST_SUITE
