name: Run Browser Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: Which test suites to run
        type: choice
        default: browser
        options:
          - browser
          - accessibility
          - browser and accessibility

permissions:
  id-token: write
  contents: read

concurrency:
  group: browser-tests
  cancel-in-progress: false

jobs:
  upload-artifact:
    name: Upload artifact for both tests to use
    uses: ./.github/workflows/upload-artifact-for-browser-test.yml

  browser-tests:
    name: Browser tests
    needs: upload-artifact
    if: inputs.suite == 'browser' || inputs.suite == 'browser and accessibility'
    uses: ./.github/workflows/browser-test-suite.yml
    with:
      build-artifact: false
      suite: browser

  accessibility-tests:
    name: Accessibility tests
    needs: upload-artifact
    if: inputs.suite == 'accessibility' || inputs.suite == 'browser and accessibility'
    uses: ./.github/workflows/browser-test-suite.yml
    with:
      build-artifact: false
      suite: accessibility
